/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * greeter.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface GreeterHelloRequest
 */
export interface GreeterHelloRequest {
    /**
     * 
     * @type {string}
     * @memberof GreeterHelloRequest
     */
    name?: string;
}

/**
 * 
 * @export
 * @interface GreeterHelloResponse
 */
export interface GreeterHelloResponse {
    /**
     * 
     * @type {string}
     * @memberof GreeterHelloResponse
     */
    greeting?: string;
}


/**
 * GreeterApi - fetch parameter creator
 * @export
 */
export const GreeterApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GreeterHelloRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hello(body: GreeterHelloRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling hello.');
            }
            const localVarPath = `/api/greeter/hello`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = JSON.stringify(body || {});

            localVarRequestOptions.credentials = 'same-origin'

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GreeterApi - functional programming interface
 * @export
 */
export const GreeterApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GreeterHelloRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hello(body: GreeterHelloRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GreeterHelloResponse> {
            const localVarFetchArgs = GreeterApiFetchParamCreator(configuration).hello(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * GreeterApi - factory interface
 * @export
 */
export const GreeterApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {GreeterHelloRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hello(body: GreeterHelloRequest, options?: any) {
            return GreeterApiFp(configuration).hello(body, options)(fetch, basePath);
        },
    };
};

/**
 * GreeterApi - object-oriented interface
 * @export
 * @class GreeterApi
 * @extends {BaseAPI}
 */
export class GreeterApi extends BaseAPI {
    /**
     * 
     * @param {} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GreeterApi
     */
    public hello(body: GreeterHelloRequest, options?: any) {
        return GreeterApiFp(this.configuration).hello(body, options)(this.fetch, this.basePath);
    }

}

